Massively updated Docksal config to add fin refresh, sequelpro, etc.

diff --git a/.docksal/commands/behat b/.docksal/commands/behat
--- a/.docksal/commands/behat
+++ b/.docksal/commands/behat
@@ -1,10 +1,16 @@
 #!/usr/bin/env bash
 
+#: exec_target = cli
+
 ## Run project's Behat tests.
 ##
-## Usage: fin behat [--path=path] [arguments]
+## Usage: fin behat [--profile=profile] [--path=path] [arguments]
 ##
-## path defaults to tests/behat
+## path     defaults to tests/behat
+## profile  defaults to docksal
+
+# Abort if anything fails
+set -e
 
 # Environment variables passed from fin:
 #
@@ -12,21 +18,42 @@
 #   $VIRTUAL_HOST - (string) ex. projectname.docksal
 #   $DOCROOT - name of the docroot folder
 #   $DOCKER_RUNNING - (string) "true" or "false"
-DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
-SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
-BEHAT_PATH="${DOCROOT_PATH}/private/tests/behat"
-FIN_BEHAT_PATH="/var/www/private/tests/behat"
 
-if [[ ! -f "$BEHAT_PATH/behat.yml" ]]; then
-	echo "Could not find behat.yml. Creating..."
-	cp $BEHAT_PATH/behat.template.yml $BEHAT_PATH/sitefarm/behat.yml
+params=''
+path='tests'
+profile=docker
+file=behat.yml
+for i in "$@"; do
+	case "$i" in
+	    --profile=*)
+            profile="${i#*=}"
+            ;;
+		--path=*)
+			path="${i#*=}"
+			;;
+		--file=*)
+			file="${i#*=}"
+			;;
+		*)
+			params="$params$i "
+			;;
+	esac;
+done
+
+behat_yml_path="${PROJECT_ROOT}/${path}/${file}"
+
+if [[ ! -f "${behat_yml_path}" ]]; then
+	echo "Could not find ${behat_yml_path}"
+	exit 1
 fi
 
-cd $DOCROOT_PATH
-# Make sure Composer dependencies are installed
-if [[ ! -d "$BEHAT_PATH/vendor" ]]; then
-	fin exec "cd $FIN_BEHAT_PATH && composer install --prefer-source --no-interaction"
+if ${VNC_PORT_MAPPING%\:5900*}; then
+    # Launch VNC viewer
+    VNC_URL="vnc://:secret@${VIRTUAL_HOST}:${VNC_PORT_MAPPING%\:5900*}"
+    echo "VNC URL: ${VIRTUAL_HOST}:${VNC_PORT_MAPPING%\:5900*}"
+    echo "Password: secret"
+    # open "$VNC_URL"
 fi
 
 # Launch Behat tests
-fin exec "cd $FIN_BEHAT_PATH ; bin/behat -p docker $@"
+cd ${PROJECT_ROOT}/${path} && /var/www/vendor/bin/behat --tags="~@ignore" --config ${behat_yml_path} -p ${profile} ${params}
